version: "3.9"
services:
  db:
    image: postgres
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_PORT=$POSTGRES_PORT
    - POSTGRES_DB=$POSTGRES_DB
    - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
    volumes:
    - "./_data:/var/lib/postgresql/data/"
    ports:
    - "5432:5432"
    networks:
    - dbadmin
  server:
    build:
      context: .
      dockerfile: dockerfile.golang
    depends_on:
      - db
    ports:
    - "8080:8080"
    networks:
    - api
    - dbadmin
networks:
  api:
  dbadmin:
