version: "3.9"
services:
  # logstash:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.logstash
  #   networks:
  #   - logging
  redis:
    image: redis
    networks:
    - tokensaving
  db:
    image: postgres
    environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_USER=$POSTGRES_USER
    - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    - POSTGRES_PORT=$POSTGRES_PORT
    - POSTGRES_DB=$POSTGRES_DB
    - POSTGRES_SCHEMA=$POSTGRES_SCHEMA
    volumes:
    - "./_data:/var/lib/postgresql/data/"
    ports:
    - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
    - dbadmin
  server:
    build:
      context: .
      dockerfile: dockerfile.golang
    depends_on:
      # - logstash
      - redis
      - db
    ports:
    - 8080:8080
    networks:
    - api
    #- logging
    - tokensaving
    - dbadmin
  nextjs:
    build:
      context: .
      dockerfile: dockerfile.nextjs
    depends_on:
      - server
    networks:
    - webproxy
    - api
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    depends_on:
      - nextjs
    ports:
    - "80:80"
    networks:
    - webproxy
networks:
  webproxy:
  api:
  #logging:
  tokensaving:
  dbadmin:
