FROM golang:1.17.5 as build
WORKDIR /app

# add go modules lockfiles
COPY go.mod go.sum ./
RUN go mod download

# prefetch the binaries, so that they will be cached and not downloaded on each change
RUN go run github.com/prisma/prisma-client-go prefetch

COPY . .

RUN go generate ./...

RUN go build -o /main .

CMD ["/main"]
